/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c
 *
 */

export type Json = unknown;

// Table account
export interface Account {
  id: string;
  accountId: string;
  providerId: string;
  userId: string;
  accessToken: string | null;
  refreshToken: string | null;
  idToken: string | null;
  accessTokenExpiresAt: Date | null;
  refreshTokenExpiresAt: Date | null;
  scope: string | null;
  password: string | null;
  createdAt: Date;
  updatedAt: Date;
}
export interface AccountInput {
  id: string;
  accountId: string;
  providerId: string;
  userId: string;
  accessToken?: string | null;
  refreshToken?: string | null;
  idToken?: string | null;
  accessTokenExpiresAt?: Date | null;
  refreshTokenExpiresAt?: Date | null;
  scope?: string | null;
  password?: string | null;
  createdAt?: Date;
  updatedAt: Date;
}
const account = {
  tableName: "account",
  columns: [
    "id",
    "accountId",
    "providerId",
    "userId",
    "accessToken",
    "refreshToken",
    "idToken",
    "accessTokenExpiresAt",
    "refreshTokenExpiresAt",
    "scope",
    "password",
    "createdAt",
    "updatedAt",
  ],
  requiredForInsert: ["id", "accountId", "providerId", "userId", "updatedAt"],
  primaryKey: "id",
  foreignKeys: {},
  $type: null as unknown as Account,
  $input: null as unknown as AccountInput,
} as const;

// Table booking
export interface Booking {
  id: string;
  userId: string;
  carId: string;
  startDate: Date;
  endDate: Date;
  totalPrice: number;
  status: string;
  createdAt: Date;
  updatedAt: Date;
}
export interface BookingInput {
  id: string;
  userId: string;
  carId: string;
  startDate: Date;
  endDate: Date;
  totalPrice: number;
  status: string;
  createdAt?: Date;
  updatedAt?: Date;
}
const booking = {
  tableName: "booking",
  columns: [
    "id",
    "userId",
    "carId",
    "startDate",
    "endDate",
    "totalPrice",
    "status",
    "createdAt",
    "updatedAt",
  ],
  requiredForInsert: [
    "id",
    "userId",
    "carId",
    "startDate",
    "endDate",
    "totalPrice",
    "status",
  ],
  primaryKey: "id",
  foreignKeys: {
    userId: { table: "user", column: "id", $type: null as unknown as User },
    carId: { table: "car", column: "id", $type: null as unknown as Car },
  },
  $type: null as unknown as Booking,
  $input: null as unknown as BookingInput,
} as const;

// Table branch
export interface Branch {
  id: string;
  name: string;
  address: string;
  city: string;
  province: string;
  postalCode: string;
  createdAt: Date;
  updatedAt: Date;
}
export interface BranchInput {
  id: string;
  name: string;
  address: string;
  city: string;
  province: string;
  postalCode: string;
  createdAt?: Date;
  updatedAt?: Date;
}
const branch = {
  tableName: "branch",
  columns: [
    "id",
    "name",
    "address",
    "city",
    "province",
    "postalCode",
    "createdAt",
    "updatedAt",
  ],
  requiredForInsert: [
    "id",
    "name",
    "address",
    "city",
    "province",
    "postalCode",
  ],
  primaryKey: "id",
  foreignKeys: {},
  $type: null as unknown as Branch,
  $input: null as unknown as BranchInput,
} as const;

// Table car
export interface Car {
  id: string;
  branchId: string;
  brand: string;
  model: string;
  transmission: string;
  fuelType: string;
  passengerCapacity: number;
  bodyType: string;
  carbonEmissions: number;
  pricePerDay: number;
  available: boolean;
  images: string | null;
  reviews?: Review[]; // Added reviews field
  createdAt: Date;
  updatedAt: Date;
}
export interface CarInput {
  id: string;
  branchId: string;
  brand: string;
  model: string;
  transmission: string;
  fuelType: string;
  passengerCapacity: number;
  bodyType: string;
  carbonEmissions: number;
  pricePerDay: number;
  available?: boolean;
  images?: string | null;
  createdAt?: Date;
  updatedAt?: Date;
}
const car = {
  tableName: "car",
  columns: [
    "id",
    "branchId",
    "brand",
    "model",
    "transmission",
    "fuelType",
    "passengerCapacity",
    "bodyType",
    "carbonEmissions",
    "pricePerDay",
    "available",
    "images",
    "createdAt",
    "updatedAt",
  ],
  requiredForInsert: [
    "id",
    "branchId",
    "brand",
    "model",
    "transmission",
    "fuelType",
    "passengerCapacity",
    "bodyType",
    "carbonEmissions",
    "pricePerDay",
  ],
  primaryKey: "id",
  foreignKeys: {
    branchId: {
      table: "branch",
      column: "id",
      $type: null as unknown as Branch,
    },
  },
  $type: null as unknown as Car,
  $input: null as unknown as CarInput,
} as const;

// Table reset_tokens
export interface ResetTokens {
  user_id: string;
  token: string;
  expires_at: Date;
}
export interface ResetTokensInput {
  user_id: string;
  token: string;
  expires_at: Date;
}
const reset_tokens = {
  tableName: "reset_tokens",
  columns: ["user_id", "token", "expires_at"],
  requiredForInsert: ["user_id", "token", "expires_at"],
  primaryKey: "user_id",
  foreignKeys: {},
  $type: null as unknown as ResetTokens,
  $input: null as unknown as ResetTokensInput,
} as const;

// Table review
export interface Review {
  userName: string;
  id: string;
  userId: string;
  carId: string;
  rating: number;
  comment: string | null;
  createdAt: Date;
}
export interface ReviewInput {
  id: string;
  userId: string;
  carId: string;
  rating: number;
  comment?: string | null;
  createdAt?: Date;
}
const review = {
  tableName: "review",
  columns: ["id", "userId", "carId", "rating", "comment", "createdAt"],
  requiredForInsert: ["id", "userId", "carId", "rating"],
  primaryKey: "id",
  foreignKeys: {
    userId: { table: "user", column: "id", $type: null as unknown as User },
    carId: { table: "car", column: "id", $type: null as unknown as Car },
  },
  $type: null as unknown as Review,
  $input: null as unknown as ReviewInput,
} as const;

// Table rewardshistory
export interface Rewardshistory {
  id: string;
  userId: string;
  bookingId: string | null;
  points: number;
  transactionType: string;
  createdAt: Date;
}
export interface RewardshistoryInput {
  id: string;
  userId: string;
  bookingId?: string | null;
  points: number;
  transactionType: string;
  createdAt?: Date;
}
const rewardshistory = {
  tableName: "rewardshistory",
  columns: [
    "id",
    "userId",
    "bookingId",
    "points",
    "transactionType",
    "createdAt",
  ],
  requiredForInsert: ["id", "userId", "points", "transactionType"],
  primaryKey: "id",
  foreignKeys: {
    userId: { table: "user", column: "id", $type: null as unknown as User },
    bookingId: {
      table: "booking",
      column: "id",
      $type: null as unknown as Booking,
    },
  },
  $type: null as unknown as Rewardshistory,
  $input: null as unknown as RewardshistoryInput,
} as const;

// Table session
export interface Session {
  id: string;
  expiresAt: Date;
  token: string;
  createdAt: Date;
  updatedAt: Date;
  ipAddress: string | null;
  userAgent: string | null;
  userId: string;
  impersonatedBy: string | null;
}
export interface SessionInput {
  id: string;
  expiresAt: Date;
  token: string;
  createdAt?: Date;
  updatedAt: Date;
  ipAddress?: string | null;
  userAgent?: string | null;
  userId: string;
  impersonatedBy?: string | null;
}
const session = {
  tableName: "session",
  columns: [
    "id",
    "expiresAt",
    "token",
    "createdAt",
    "updatedAt",
    "ipAddress",
    "userAgent",
    "userId",
    "impersonatedBy",
  ],
  requiredForInsert: ["id", "expiresAt", "token", "updatedAt", "userId"],
  primaryKey: "id",
  foreignKeys: {},
  $type: null as unknown as Session,
  $input: null as unknown as SessionInput,
} as const;

// Table user
export interface User {
  id: string;
  name: string;
  email: string;
  emailVerified: boolean;
  image: string | null;
  createdAt: Date;
  updatedAt: Date;
  role: string | null;
  rewards: number | null;
  banned: boolean | null;
  banReason: string | null;
  banExpires: Date | null;
}
export interface UserInput {
  id: string;
  name: string;
  email: string;
  emailVerified: boolean;
  image?: string | null;
  createdAt?: Date;
  updatedAt?: Date;
  role?: string | null;
  rewards?: number | null;
  banned?: boolean | null;
  banReason?: string | null;
  banExpires?: Date | null;
}
const user = {
  tableName: "user",
  columns: [
    "id",
    "name",
    "email",
    "emailVerified",
    "image",
    "createdAt",
    "updatedAt",
    "role",
    "rewards",
    "banned",
    "banReason",
    "banExpires",
  ],
  requiredForInsert: ["id", "name", "email", "emailVerified"],
  primaryKey: "id",
  foreignKeys: {},
  $type: null as unknown as User,
  $input: null as unknown as UserInput,
} as const;

// Table verification
export interface Verification {
  id: string;
  identifier: string;
  value: string;
  expiresAt: Date;
  createdAt: Date;
  updatedAt: Date;
}
export interface VerificationInput {
  id: string;
  identifier: string;
  value: string;
  expiresAt: Date;
  createdAt?: Date;
  updatedAt?: Date;
}
const verification = {
  tableName: "verification",
  columns: ["id", "identifier", "value", "expiresAt", "createdAt", "updatedAt"],
  requiredForInsert: ["id", "identifier", "value", "expiresAt"],
  primaryKey: "id",
  foreignKeys: {},
  $type: null as unknown as Verification,
  $input: null as unknown as VerificationInput,
} as const;

export interface TableTypes {
  account: {
    select: Account;
    input: AccountInput;
  };
  booking: {
    select: Booking;
    input: BookingInput;
  };
  branch: {
    select: Branch;
    input: BranchInput;
  };
  car: {
    select: Car;
    input: CarInput;
  };
  reset_tokens: {
    select: ResetTokens;
    input: ResetTokensInput;
  };
  review: {
    select: Review;
    input: ReviewInput;
  };
  rewardshistory: {
    select: Rewardshistory;
    input: RewardshistoryInput;
  };
  session: {
    select: Session;
    input: SessionInput;
  };
  user: {
    select: User;
    input: UserInput;
  };
  verification: {
    select: Verification;
    input: VerificationInput;
  };
}

export const tables = {
  account,
  booking,
  branch,
  car,
  reset_tokens,
  review,
  rewardshistory,
  session,
  user,
  verification,
};
